import { Navbar } from "@/components/landing/navbar";
import { Footer } from "@/components/landing/footer";

export default function TermsPage() {
    return (
        <div className="flex min-h-screen flex-col">
            <Navbar />
            <main className="flex-1 container mx-auto px-4 py-12 max-w-3xl">
                <h1 className="text-3xl font-bold mb-8 text-slate-900">Terms of Service</h1>

                <div className="prose prose-slate max-w-none text-slate-800">
                    <p className="lead">
                        Last updated: {new Date().toLocaleDateString()}
                    </p>

                    <p>
                        Please read these Terms of Service (&quot;Terms&quot;) carefully before using the SmartPrints UK website and services.
                    </p>

                    <h2 className="text-xl font-semibold mt-6 mb-4">1. Acceptance of Terms</h2>
                    <p>
                        By accessing or using our service, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the service.
                    </p>

                    <h2 className="text-xl font-semibold mt-6 mb-4">2. Description of Service</h2>
                    <p>
                        SmartPrints UK provides an AI-powered tool for parents to generate educational worksheets and activities. The service is provided on an &quot;as-is&quot; and &quot;as-available&quot; basis.
                    </p>

                    <h2 className="text-xl font-semibold mt-6 mb-4">3. Subscriptions and Payments</h2>
                    <p>
                        Some parts of the Service are billed on a subscription basis (&quot;Subscription(s)&quot;). You will be billed in advance on a recurring and periodic basis (such as monthly or annually).
                    </p>
                    <ul className="list-disc pl-6 mb-4">
                        <li><strong>Free Tier:</strong> Limited to a specific number of generations.</li>
                        <li><strong>Pro Tier:</strong> Requires a paid subscription for unlimited access.</li>
                    </ul>

                    <h2 className="text-xl font-semibold mt-6 mb-4">4. Refunds</h2>
                    <p>
                        Due to the digital nature of our products (instant generation of content), we generally do not offer refunds once a subscription period has started, except as required by UK consumer law. You may cancel your subscription at any time to prevent future billing.
                    </p>

                    <h2 className="text-xl font-semibold mt-6 mb-4">5. Intellectual Property</h2>
                    <p>
                        The content generated by our AI for you is yours to use for personal, non-commercial purposes. You may not resell the generated worksheets as your own standalone product without express permission.
                    </p>

                    <h2 className="text-xl font-semibold mt-6 mb-4">6. Limitation of Liability</h2>
                    <p>
                        In no event shall SmartPrints UK, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses.
                    </p>

                    <h2 className="text-xl font-semibold mt-6 mb-4">7. Contact Us</h2>
                    <p>
                        If you have any questions about these Terms, please contact us at support@smartprints.uk.
                    </p>
                </div>
            </main>
            <Footer />
        </div>
    );
}
